### PR TITLE
Underwater rendering with partially submerged view

### PR DESCRIPTION
**Pull request by huwb**
From #70 

Renders a curtain of geometry below water surface to do water fogging/scattering etc. Looks something like this:

image

The code copies the material params onto the underwater material so that they match (when they dont match it creates weird rendering issues). Shader features (like 'Shadowing') are still there and need to be matched manually as these can't be toggled at runtime in standalone builds.

### CODE REVIEW

**Comment by holdingjason** [comment]
@huwb Ok pulled the latest and see now that all the values for the underwater skirt are toggles so that I am guessing its syncing up with the ocean shader values.  So anything we want to do to the underwater look would need to be changed in the main water shader ie color etc correct?  I am guessing this is so that we get nice blending between the surface and the underwater skirt?

Issue: Changing transparency on the ocean shader only seems to effect the surface water and not the skirt.  I would has expected the skirt to also become more or less transparent ie can see farther (or less) based on the transparency value, this was I believe how it worked before when they were separate and we needed to sync them manually.  Appears something may have broken in the skirt for this.

Along these same lines does the transparency setting for the skirt (assuming it was bugged above) change at all as you go deeper etc.  I think it is suppose to work as a constant value correct?  Not sure how lighting etc effect it, if at all.  Like what would happen if I bring a light underwater with me for instance.

Minor issue.  I am wondering if we could add something like a depth color similar to what we do with the ocean shader for shallow vs deep water.  Thinking it could allow the skirt color to change as we go deeper.  So near the surface would work like we have ie match surface values, as we go deeper could change.  Just a thought.

**Comment by holdingjason** [comment]
@huwb Ok see what the problem is with transparency and guessing all the settings work this way.  The "copy" occurs on start and so I was changing values at runtime on the ocean shader and not seeing those updated on the fly.  If I mod them first then run it works.  So if I want to change values on fly I am guessing I would do it the old fashion way and update both the shaders at that point via code?

I will check into that but guessing that is correct.

**Comment by holdingjason** [comment]
Does the transparency setting for the skirt (assuming it was bugged above) change at all as you go deeper etc.  I think it is suppose to work as a constant value correct?  Not sure how lighting etc effect it, if at all.  Like what would happen if I bring a light underwater with me for instance.

Minor issue.  I am wondering if we could add something like a depth color similar to what we do with the ocean shader for shallow vs deep water.  Thinking it could allow the skirt color to change as we go deeper.  So near the surface would work like we have ie match surface values, as we go deeper could change.  Just a thought.  Honestly I guess this might fall under custom requirement and probably would be fairly easy for us to add to the skirt shader manually.  Just check depth and lerp in a color mod probably.  Does that sound right to you?

**Comment by huwb** [comment]
Yes i think you could add to ScatterColour and mix in you own stuff based on depth (i_cameraPos.y compared to _OceanCenterPosWorld.y). I'm not sure i'd add this to core Crest, for the time being anyway..

Alright i think tidy enough and good to go, merging.

**Pull request merged**
