### PR TITLE
Implement compute shaders for applicable LodData

### LINKED ISSUE #214: Move GPU computations to compute shaders where suitable
Breakdown of tasks that need completing currently being contructed.

Being worked on in the `feature/compute-shaders` branch.

### PR DESCRIPTION
**Pull request by moosichu**
In progress, see discussion.

Resolves #214.

### CODE REVIEW

**Comment by moosichu** [comment]
The current state of the PR is as follows:

- Compute shaders varients have been implemented for:
    - `AnimWavesGerstnerBatch`
    - `ShapeGerstnerBatch` and
   - `UpdateFoam`

Within the existing command buffer structure.

There are now a spectrum of options avaiable with regards to implementating compute shaders, each with their own tradeoffs. The goal of creating the PR now is to allow us to properly evaluate those options and decide which tradeoffs are worth it. There are also questions that need to be answered as well.

The options lie on some continuum between these options:
 - Not support compute shaders at all
 - Supporting compute shaders for LodData and not others
 - Supporting compute shaders for all LodData
- Supporting both compute shaders and the traditional pipeline

The following questions could help us decide which of these options to go with:
- What is the maintenance overhead of managing one of these systems, or both?
- What benefits does a CS pipeline provide over a traditional one?
- What future benefits could a CS pipepine provide over a traditional one?
- What benefits does a traditional pipeline provide over a CS one?
- How would we handle CS variants, as Unity unfortunately doesn't support this natively. :(
- Are there alternatives to using geometry for some of the LodData which can be enhanced/depend on rendering it?

**Comment by moosichu** [comment]
We also need to get compute shaders tested on different devices, to ensure that they are functional where we want them to be if we want to move forward with them.

**Comment by huwb** [comment]
Thanks Tom. What are CS variants btw?

**Comment by dizzy2003** [comment]
I just tried this branch on switch, release build ran fine, when I tried to do a dev build it crashed with the below call stack, which I know isnt very useful..  (Unity 2018.3.9f1)

Stack trace:
  0x00000073F26D33E0 _ZN15GfxDeviceSwitch13debugCallbackE22NVNdebugCallbackSource20NVNdebugCallbackTypei24NVNdebugCallbackSeverityPKcPv+0x100
  0x00000073F8F52DEC (unknown)
  0x00000073F8F1C3D4 NvWsiSetCallbacks+0x5024 (too far)
  0x00000073F26EC8A8 _ZN15GfxDeviceSwitch22UpdateComputeResourcesERK22ComputeShaderResources+0x2B8
  0x00000073F2936B64 _ZN15GfxDeviceWorker10RunCommandER20ThreadedStreamBuffer+0x5234
  0x00000073F29393E4 _ZN15GfxDeviceWorker6RunExtER20ThreadedStreamBuffer+0x84
  0x00000073F2939350 _ZN15GfxDeviceWorker3RunEv+0xB0
  0x00000073F293162C _ZN15GfxDeviceWorker18RunGfxDeviceWorkerEPv+0xC
  0x00000073F1D75F2C _ZN6Thread16RunThreadWrapperEPv+0x44C
  0x00000073F8E06618 (unknown)
  0x00000073F8E0C724 (unknown)

**Comment by dizzy2003** [comment]
Ps4 crashes with or without ENABLE_COMPUTE_SHADERS

will double check the current main branch works on ps4



ArgumentNullException: Value cannot be null.
Parameter name: mesh
  at UnityEngine.Playables.PlayableDirector.SendOnPlayableDirectorStop () [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.Playables.PlayableDirector.SendOnPlayableDirectorStop () [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.Rendering.CommandBuffer.DrawMesh (UnityEngine.Mesh mesh, UnityEngine.Matrix4x4 matrix, UnityEngine.Material material, System.Int32 submeshIndex, System.Int32 shaderPass, UnityEngine.MaterialPropertyBlock properties) [0x00000] in <00000000000000000000000000000000>:0 
  at Crest.ShapeGerstnerBatched.BuildCommandBuffer (System.Int32 lodIdx, Crest.OceanRenderer ocean, UnityEngine.Rendering.CommandBuffer buf) [0x00000] in <00000000000000000000000000000000>:0 
  at Crest.LodDataMgrAnimWaves.BuildCommandBuffer (Crest.OceanRenderer ocean, UnityEngine.Rendering.CommandBuffer buf) [0x00000] in <00000000000000000000000000000000>:0 
  at Crest.BuildCommandBuffer.Build (Crest.OceanRenderer ocean, UnityEngine.Rendering.CommandBuffer buf) [0x00000] in <00000000000000000000000000000000>:0 
  at Crest.BuildCommandBuffer.LateUpdate () [0x00000] in <00000000000000000000000000000000>:0 
  at System.Dynamic.Utils.ListProvider`1[T].get_ElementCount () [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.XR.XRSettings.get_renderViewportScaleInternal () [0x00000] in <00000000000000000000000000000000>:0 
System.Dynamic.Utils.ListProvider`1:get_ElementCount()
UnityEngine.XR.XRSettings:get_renderViewportScaleInternal()
 
(Filename: currently not available on il2cpp Line: -1)

ArgumentNullException: Value cannot be null.
Parameter name: mesh
  at UnityEngine.Playables.PlayableDirector.SendOnPlayableDirectorStop () [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.Playables.PlayableDirector.SendOnPlayableDirectorStop () [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.Rendering.CommandBuffer.DrawMesh (UnityEngine.Mesh mesh, UnityEngine.Matrix4x4 matrix, UnityEngine.Material material, System.Int32 submeshIndex, System.Int32 shaderPass, UnityEngine.MaterialPropertyBlock properties) [0x00000] in <00000000000000000000000000000000>:0 
  at Crest.ShapeGerstnerBatched.BuildCommandBuffer (System.Int32 lodIdx, Crest.OceanRenderer ocean, UnityEngine.Rendering.CommandBuffer buf) [0x00000] in <00000000000000000000000000000000>:0 
  at Crest.LodDataMgrAnimWaves.BuildCommandBuffer (Crest.OceanRenderer ocean, UnityEngine.Rendering.CommandBuffer buf) [0x00000] in <00000000000000000000000000000000>:0 
  at Crest.BuildCommandBuffer.Build (Crest.OceanRenderer ocean, UnityEngine.Rendering.CommandBuffer buf) [0x00000] in <00000000000000000000000000000000>:0 
  at Crest.BuildCommandBuffer.LateUpdate () [0x00000] in <00000000000000000000000000000000>:0 
  at System.Dynamic.Utils.ListProvider`1[T].get_ElementCount () [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.XR.XRSettings.get_renderViewportScaleInternal () [0x00000] in <00000000000000000000000000000000>:0 
System.Dynamic.Utils.ListProvider`1:get_ElementCount()
UnityEngine.XR.XRSettings:get_renderViewportScaleInternal()

**Comment by dizzy2003** [comment]
Just tried master branch on ps4 and it ran fine

**Comment by moosichu** [comment]
Thanks @dizzy2003, will have a look at this when I have the opportunity. 👍

**Comment by huwb** [comment]
Unfortunately i know what this is - there's a field like 'Raster mesh'  or something on the shape gerstner batched script. It is usually set to unity's default Quad mesh. Sometimes that reference gets broken and it will be Missing or Unassigned in the scene and needs to be set back to Quad.

I htink i have code lying around somewhere that negates the need to use a Quad here at all (constructs it own quad), ill take a look

**Comment by moosichu** [comment]
We have learnt a lot of useful info from this PR, but will not be merging/working on it for now while we explore other options (as mentioned in #214).

**Comment by huwb** [comment]
Thought I should explain a bit what we discussed and where we are with this.

The goals with this branch are to get get familiar with compute shaders, see what can be moved to compute and what advantages that would bring, and ultimately see if the entire update can be moved to async compute.

The passes that don't rely on geometry such as updating foam sim and wave sim etc can be moved to compute. Many other components of the ocean update rely on geometry, including populating the ocean depths which is one of the first passes, so this stuff needs to stay rasterized. Therefore it doesnt seem to be an option to do this with compute (and therefore async compute..) without some fairly radical changes.

It might still be possible to run parts of if using (async) compute. We did an initial test and didn't see a performance improvement, but didnt go really deep on figuring out why. We leave the door open to doing this in the future.

For now we discussed parking this and trying other approaches to speed up the ocean update. One promising direction is to update multiple data lods simultaneously using either MRT or texture arrays and is something we're looking into next.

**Comment by moosichu** [comment]
One of the benefits of these changes would be the fact that we would be able to execute commands on the [`AsyncComputeQueue`](https://docs.unity3d.com/ScriptReference/Graphics.ExecuteCommandBufferAsync.html) instead of the regular queue.

This would simply be a matter of creating seperate commadn buffer(s?) in `BuildCommandBuffer.cs`, and setting appropriate [graphics fences](https://docs.unity3d.com/ScriptReference/Rendering.GraphicsFence.html) within them.

Then just execute each command buffer on the appropriate queus.

**Comment by moosichu** [comment]
Closing as this change is superseded by #272.

**Pull request closed without merging**
