### PR TITLE
Fix shadows not removing caustics in underwater curtain

### PR DESCRIPTION
**Pull request by moosichu**
Before:
image

After:
image

### CODE REVIEW

**Comment by moosichu** [comment]
I don't know if my solution is hacky or not, and feedback appreciated!

**Comment by huwb** [comment]
Ah good find. Attempt at a (very tired) review:

Should it just sample from that one lod? Lod index 1? Not saying its wrong but if you could write a few words about how you arrived at that it would be useful, thanks.

You shouldnt need the #define i dont think, you can pass it in as an argument to the function. if the parameter is always constant the shader compiler will optimize out the branch anyway so branch cost should not be an issue.

Minor nitpicks, If you get a chance could you look at the whitespace changes and i think "underwater" is one word, i remember googling that and deciding whether to capitalise!

**Comment by moosichu** [comment]
Sure, I will sort out whitespace changes.

With regards to underwater spelling, I was making it consistent with other functions in the file, but will change those instead.

I can have a look at sampling. I was simply applying the principles found here:
```
if (i_underWater)
	{
		// compute scatter colour from cam pos. two scenarios this can be called:
		// 1. rendering ocean surface from bottom, in which case the surface may be some distance away. use the scatter
		//    colour at the camera, not at the surface, to make sure its consistent.
		// 2. for the underwater skirt geometry, we don't have the lod data sampled from the verts with lod transitions etc,
		//    so just approximate by sampling at the camera position.
		// this used to sample LOD1 but that doesnt work in last LOD, the data will be missing.
		const float2 uv_0 = LD_0_WorldToUV(i_cameraPos.xz);
		float seaFloorHeightAboveBaseline = 0.;
		SampleSeaFloorHeightAboveBaseline(_LD_Sampler_SeaFloorDepth_0, uv_0, 1.0, seaFloorHeightAboveBaseline);
		depth = DEPTH_BASELINE - seaFloorHeightAboveBaseline;
		waveHeight = 0.;

		fixed2 shadowSoftHard = 0.;
		SampleShadow(_LD_Sampler_Shadow_0, uv_0, 1.0, shadowSoftHard);
		shadow = 1. - shadowSoftHard.x;
}
```
In the `ScatterColour` function.

I will make the underwater a function param.

Will do all of the above, tomorrow.

**Comment by huwb** [comment]
Thanks, thats the background i could not remember! if you could copy that last line of the comment about lod1 being missing and put it with your code,, that would be great.

Sorry about the underwater inconsistency :( . yeah i htink it should be one word. thanks.

With that i reckon its good to merge but id like to have a test with it, should be able to tonight.

Thanks!

**Comment by huwb** [comment]
Looks good to me, tried it locally and it seems to work for me. Go ahead and merge it!

**Pull request merged**
