### PR TITLE
Refactor/move to command buffers

### LINKED ISSUE #44: Wave sim intensity is very frame-rate dependent
Hi @huwb !

Looks like Wave sim/Foam sim intensity are very related to framerate.
I have tested this on 3 diferent machines:

* Machine 1: Core i5, Intel HD 620 (Around 20 fps avg)
* Machine 2: Core i7 7500, Geforce GTX 950M (Around 35 fps avg) (approx)
* Machine 3: Core i7 8700, Geforce GTX 1080 (+80 fps)

On machine 1, there is a lot of foam just after starting accelerating the ship a little, and after get some speed, the generated wave is way higher (in height) than desired.

On machine 2, is also noticeable there is a lot more foam than normal, and that waves go too up as well, but not as much as on machine 1.

On machine 3, there is almost no foam (unless you go pretty fast and turning), and wave sim is way smaller, not getting as high as any of the other machines.

I've just double checked this on latest https://github.com/huwb/crest-oceanrender/commit/d4d8536507f7237f75f94a473331a6a296e506a2 commit from master.

I think that some time-dependent values are not multiplied by `Time.deltaTime`, or maybe we are mixing fixed time step with regular time steps. I'll try to figure out what is causing this.

Thank you!

### PR DESCRIPTION
**Pull request by huwb**
(PR Status: tested on branch, ready for further testing or merging into master)

This PR refactors the entire loddata system. I'm moving it to a component manager system because it was wasteful having gameobjects+cameras for each lod data type which were not necessary. 

The new system will build a commandbuffer for all the loddata, should be more controllable, simpler, cheaper, and should allow me to run the wave sim at higher frequency which should close #44 and #106, and on top of all that it will be a big step towards scriptable render pipeline support. It also removes the need for layers completely (#61).

Perf has improved signficantly in a standalone build running at 320x200 resolution, i get 580fps on my laptop. When i recently did this test last time, i got 360fps (#79), so this PR shaves 1ms off the CPU frame time for me.

Impact:
* Render Ocean Depth script changed to Register Ocean Depth Input, to bring it in line with new naming conventions. Usages of the old script need to be switched to the new.
* No more layers - the ApplyLayers component has been removed completely, and will give unassigned script warnings if you are using them in your project. If you had cull include/exclude layers specified they should be applied directly to the culling mask on the camera. Simply removing the unassigned scripts should be enough to get going in most cases.
* I did a big rename and cleanup of shaders and materials which may produce breakages or merge conflicts. This probably mostly affects usages of shaders that add foam/waves/flow/etc. These were not widely used partly because they were confusingly named and inconsistent, which was the reason for this cleanup.
* Script execution order is simplified and made explicit. I've added documentation to the TECHNOLOGY.md page.

### CODE REVIEW

**Comment by huwb** [comment]
Finally i think im at the end of this - i just have a few last small tweaks to example data.

It may need some fixup in your projects - see the impact above. If anyone is keen and has time to early-adopt this to help me test the changes, let me know. If not then i'll merge it in to master some time soon.

@moosichu @holdingjason @midda-c @dizzy2003 @mschwarz1

**Comment by holdingjason** [comment]
sure I can pull it over and give it a go.  This is all in refactor/move-to-command-buffers so will yank it from there.

**Comment by Tsetso** [comment]
I'll do my best to try out the latest features as well. Already pulling any new changes aside...

**Comment by moosichu** [comment]
Testing it out now

**Comment by moosichu** [comment]
There's a lot of stuff to work through, and although I'm the inevitable bugs crop-up here and there, it all looks good to me. Tested out upgrading to this on a small project and it worked pretty well!

**Comment by huwb** [comment]
Thanks @moosichu! If anyone else has feedback (or wants more time to test) please let me know.

**Comment by holdingjason** [comment]
A bit more time.  Moved things over into the project but getting a bunch of warnings about my floating stuff and not seeing any waves, acting like its just calm water right now.  Not sure what is going on so comparing my stuff to your example project to see.

Validation failed: NoDataAtThisPosition. See comments on the AvailabilityResult enum.
UnityEngine.Debug:LogWarning(Object, Object)

**Comment by huwb** [comment]
Damn sorry @holdingjason - this was a todo that i didnt mark as such and it slipped through the net. The problem was that there is unfortunately no shared event between forward and deferred paths that i can hook to, so i added code to choose the event based on path with some validation to catch this kind of thing in the future. Could you please grab latest and try with that (commit referenced above)? Thanks..

**Comment by holdingjason** [comment]
Ok that seems to work fine but getting a flicker now and again.  I need to check to see if I was always getting this or not and just noticed it but I did not think so.  I believe it is related to a garbage collection issue since it seems to time up pretty well with the profiler.  It is caused by calls to GPUReadBack ie sampling water surface just like/similar to how you are doing it with the boats and the boatalignnormal script.  I used the boats example and was able to replicate the issue so you should be able to see it as well.  Basically calling it over and over in the fixedupdate as we are generates a lot of GC Allocations which eventually trigger a punch in the head GC Collect (this can 10+ milliseconds in a single frame) which I think is causing the  hiccup.

Here is the deep profile I grabbed during a normal frame (not the GC Collect one).  It is allocating about 1.4KB of memory each frame.  This is using the 3 boat scene.  This of course gets worse and worse the more things that call this sequence of course, so the more floating objects the worse this alloc gets and the more times GC Collect will get triggered and worse it will be.

I believe the issue can be tracked down to foreach loops the gremlins of memory alloc.  Basically you should only use them when your doing one off calls infrequently.  In loops or repeated calls they used to be complete death, this has been improved however here is an excellent article on which lists you can foreach and there impact.  Unfortunately it appears the sorted list is still the worst of the lot.

https://jacksondunstan.com/articles/3805

image

**Comment by holdingjason** [comment]
BTW will be out of town Thur and back next Monday so just FYI bad timing on my part.  I will be available to answer questions just wont be able to test anything but will be able to tonight and tomorrow morning my time (Las Vegas).

**Comment by holdingjason** [comment]
@huwb  Ok here is the video of the flicker.  I verified that I do not see this kind of flicker in the mail build just this one using the command buffers.  I do get a bit of a hiccup in both but its more of the normal hitch you see when frame rate drops off because of an errant process (like GC etc) vs this kind of video flicker.  

https://drive.google.com/open?id=1CyeK75aP99l_1H-a22frcLiruaZNFJzt

**Comment by holdingjason** [comment]
@huwb Got it, not related to the above issues.  I still think we have an issue with for each loops btw because I can still see decent hit 1-2 ms hit with 10+ floating objects which is mostly caused by the memory alloc.

So in the three boats scene I set this up (not sure you need these settings but whatever)

Lod Count max 16.
WavesModerateSmooth weight 1.0
Main Camera Cam Controller Lin Speed = 50

Just take off in forward direction for a bit and you will catch the flicker as I think it bounces between LODs.  Here is a video that captures it with data.

https://drive.google.com/open?id=1D85_kQ32SwdSAF9O4KWVojDfcYKZMJ2I

**Comment by huwb** [comment]
Good catch with that one frame issue. It was an update order problem, i've made the update orders simpler and explicit now.

I did a pretty ugly thing to stop garbage from sorted list. Should be good to go now.

I found another GC from a FindObjectOfType which i had neglected to clean up! This led to a good fix.

Thinking/hoping its pretty solid now. Just remembered you're out of town @holdingjason , i might merge this into master in the next day or two so i can clear this off my plate and start on other stuff. Last call for any testing!

**Comment by holdingjason** [comment]
Yep poor timing so can't test before that so go ahead.  Those we're all I noticed so should be good.

**Comment by holdingjason** [comment]
Great job btw I see a significant performance increase with this method and hope the GC stuff helps as well.

**Comment by huwb** [comment]
Merged, thanks all!

**Pull request merged**
